query1 = """
SELECT
  STRFTIME('%Y-%m-01', DATETIME(loan_timestamp, 'unixepoch')) AS MONTH,
  COUNT(DISTINCT CASE WHEN loan_status = 'declined' THEN LOAN_ID ELSE NULL END) / CAST(COUNT(DISTINCT LOAN_ID) AS FLOAT) AS DECLINED_LOANS_PERC

FROM loans
WHERE STRFTIME('%Y-%m-01', DATETIME(loan_timestamp, 'unixepoch')) in ('2019-04-01', '2019-03-01')
GROUP BY 1
ORDER BY 1 DESC
"""

query2 = """
WITH DF AS (
  SELECT
    USER_ID,
    STRFTIME('%Y-%m-%d', DATETIME(LOAN_TIMESTAMP, 'unixepoch')) as loan_date,
    LAG(STRFTIME('%Y-%m-%d', DATETIME(LOAN_TIMESTAMP, 'unixepoch'))) OVER(PARTITION BY USER_ID ORDER BY LOAN_TIMESTAMP ASC) AS PREV_LOAN_DATE,
    LOAN_ID AS LATEST_LOAN,
    LAG(LOAN_ID) OVER(PARTITION BY USER_ID ORDER BY LOAN_TIMESTAMP ASC) AS PREVIOUS_LOANID,
    ROW_NUMBER() OVER(PARTITION BY USER_ID ORDER BY LOAN_TIMESTAMP DESC)  AS RAN
  FROM loans
)
SELECT
  USER_ID,
  LATEST_LOAN AS LATEST_LOANID,
  PREVIOUS_LOANID,
  JULIANDAY(loan_date) - JULIANDAY(PREV_LOAN_DATE) AS DATE_DIFFERENCE
  
FROM DF
WHERE RAN = 1
AND PREVIOUS_LOANID IS NOT NULL
"""

query3 = """
  SELECT
    LOAN_AMOUNT
  FROM LOANS
  WHERE LOAN_STATUS != 'declined'
  GROUP BY 1
"""
query4 = """ 
WITH DF AS (
  SELECT
    CASE
      WHEN LOAN_AMOUNT > 5000 THEN 'HIGH'
      WHEN LOAN_AMOUNT > 3750 THEN 'MID'
      WHEN LOAN_AMOUNT > 2500 THEN 'MID-LOW'
    ELSE 'LOW'
    END AS TIER,
    LOAN_STATUS,
    count(loan_id) AS LOANS
  FROM LOANS
  WHERE LOAN_STATUS != 'declined'
  group by 1,2
)
SELECT 
  *
FROM (
  SELECT
    TIER,
    LOAN_STATUS,
    SUM(LOANS) OVER(PARTITION BY TIER, LOAN_STATUS),
    SUM(LOANS) OVER(PARTITION BY TIER, LOAN_STATUS) / CAST(SUM(LOANS) OVER(PARTITION BY TIER)  AS FLOAT64) AS P
    
  FROM DF
)
WHERE LOAN_STATUS = 'paid'
"""